#ifndef SERIALIZATION_CONSTS_H
#define SERIALIZATION_CONSTS_H

// Immutable consts

#define NO_POSITION_STR "-0"
#define POSITION_STR_LEN 3
#define MOVE_DATA_STR_PROMOTION_FIRST_INDEX 4
#define MOVE_DATA_STR_LEN 7
#define FILE_NAMES "abcdefgh"
#define RANK_NAMES "12345678"
#define FIRST_FILE_NAME 'a'
#define LAST_FILE_NAME 'h'
#define FIRST_RANK_NAME '1'
#define LAST_RANK_NAME '8'
#define QUEEN_PROMOTION_CHAR 'q'
#define ROOK_PROMOTION_CHAR 'r'
#define BISHOP_PROMOTION_CHAR 'b'
#define KNIGHT_PROMOTION_CHAR 'k'
#define OPTIONAL_PROMOTION_DECLARATION_CHAR '='

#endif // SERIALIZATION_CONSTS_H
