#ifndef CONSTS_H
#define CONSTS_H

#define RANKS_COUNT 8
#define FILES_COUNT 8
#define POSITIONS_COUNT RANKS_COUNT * FILES_COUNT
#define NO_POSITION 255

#define PLAYERS_COUNT 2

#define PIECE_TYPES_COUNT 6

#define PIECE_GROUP_MAX_SIZE 10

#endif // CONSTS_H
